name: Print Hello World

on:
  workflow_dispatch: 
    inputs:
      appshortcode_dp:
        description: 'Application Shortcode,data_product_name: GLSM,Service Management'
        required: true
        type: string

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
