name: Print Hello World

on:
  push:
    branches:
      - main

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
